services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Endroid\ImagePlaceholder\ImagePlaceholder: ~
    Endroid\ImagePlaceholder\Twig\Extension\ImagePlaceholderExtension: ~
